apiVersion: skaffold/v4beta3
kind: Config
manifests:
    rawYaml:
        - ./infra/k8s/*
build:
    artifacts:
        - image: belfortjoao216/backend
          context: backend
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: belfortjoao216/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '**/*.vue'
                    dest: .
